name: sundial_pointcloud_geometry_explore
channels:
  - conda-forge
  - defaults
dependencies:
  - ipyvolume
  - jupyterlab
  - pandas
  - vaex-core
  - tqdm
  - pip
  - pip:
    - pptk
    - git+https://github.com/sundial-pointcloud-geometry/ectopylasm.git#egg=ectopylasm
    - symfit
  - line_profiler
